project:
  type: website
  output-dir: docs

website:
  title: "Professor Bronson"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Case 1.qmd
        text: Case 1

format:
  html:
    theme: spacelab
    css: styles.css
    toc: true